# Generated by Django 3.1.7 on 2021-03-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20210304_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='framework',
            options={'ordering': ['language']},
        ),
    ]
