# Generated by Django 3.1.7 on 2021-03-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210307_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='github'),
        ),
    ]
