# Generated by Django 3.1.7 on 2021-03-10 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0003_auto_20210307_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('slug', models.SlugField(max_length=60, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='languages.framework')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('slug', models.SlugField(max_length=60, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('slug', models.SlugField(max_length=60, verbose_name='slug')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='educa.course', verbose_name='section')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('video', models.URLField(verbose_name='video link')),
                ('slug', models.SlugField(max_length=60, verbose_name='slug')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='educa.section')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='educa.subject'),
        ),
    ]
