# Generated by Django 3.1.7 on 2021-03-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hook',
            field=models.TextField(blank=True, verbose_name='commercial hook'),
        ),
    ]
